'''
First things to account for:
- Input/output (no tts for now)

Challenges:
- How will we have it generate a unique response based on the user's input?
- What packages will we use for tts and speech recognition?
- How will we incorporate the RasPi's?
- Will we maintain the same C++ backend/Python frontend model?

Conventions:
- Single quotes
- Single space between hashtag and comment
'''

# Clear screen
print(chr(27) + "[2J")

# Welcome statements
print('\n\033[1mWelcome to ClydeBot 2019 v0.1 ALPHA TESTING\033[0m')
print('Developed by Elias Newlin, Seth Traman, Ian Doherty, and Austin Turcotte')
print('\nType "exit" to exit the program at any time, or type "help" for help.')

# Bot response, will be artificially generated by machine learning
bot_response = 'test'

while True:
    user_input = input('\n>>User ')
    if user_input.lower() == 'exit':
        break
    elif user_input.lower() == 'help':
        print('\nClydeBot Help Materials')
        print('Command\t\tPurpose\n')
        print('exit\t\tExits the program.')
        print('help\t\tDisplays help menu.')
    else:
        print('\n>>ClydeBot', bot_response)
        
# Friendly exit message
print('Bye')